#!/bin/sh
#
# $FreeBSD: ports/www/p5-FCGI-Spawn/pkg-install,v 1.1 2010/04/14 13:58:52 skreuzer Exp $
#

if [ "$2" != "PRE-INSTALL" ]; then
    exit 0
fi

USER=fcgi
GROUP=${USER}

if ! pw groupshow "${GROUP}" 2>/dev/null 1>&2; then
	if pw groupadd ${GROUP} ; then
		echo "Added group \"${GROUP}\"."
	else
		echo "Adding group \"${GROUP}\" failed..."
		exit 1
	fi
fi

if ! pw usershow "${USER}" 2>/dev/null 1>&2; then
	if pw useradd ${USER} -g ${GROUP} -h - \
		-s "/sbin/nologin" -d "/nonexistent" \
		-c "FastCGI Spawner"; \
	then
		echo "Added user \"${USER}\"."
	else
		echo "Adding user \"${USER}\" failed..."
		exit 1
	fi
fi

exit 0
