#!/bin/sh
#
# $FreeBSD: ports/www/p5-FCGI-Spawn/pkg-deinstall,v 1.1 2010/04/14 13:58:52 skreuzer Exp $
#

if [ "$2" != "POST-DEINSTALL" ]; then
    exit 0
fi

USER=fcgi

if pw usershow "${USER}" 2>/dev/null 1>&2; then
	echo "To delete user permanently, use 'pw userdel ${USER}'. Also, unused groups of that user should be deleted, too"
fi

exit 0
